{% set name = "type-lens" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/type_lens-{{ version }}.tar.gz
  sha256: 8720176565c8129bf196fdbdb8c15fdabe150d779bbed101e6b2f418c54ed9bc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - hatchling
    - pip
  run:
    - python >=3.8,<4.0
    - eval_type_backport
    - typing_extensions >=4.1.0

test:
  imports:
    - type_lens
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/litestar-org/type-lens
  doc_url: http://docs.type-lens.litestar.dev/
  summary: Runtime type introspection utilities 
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
