schema_version: 1

context:
  name: type-lens
  version: "0.2.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/type_lens-${{ version }}.tar.gz
  sha256: 6cd32d38845c574d244c979c89c955da6e13c4aad0dc5cd08d318ba31b9cabf1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - eval_type_backport
    - typing_extensions >=4.1.0

tests:
  - python:
      imports:
        - type_lens
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Runtime type introspection utilities
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/litestar-org/type-lens
  documentation: http://docs.type-lens.litestar.dev/

extra:
  recipe-maintainers:
    - thewchan
